scoreboard teams join WileyCyote @r[team=]
scoreboard teams join Bomberman @r[team=]
scoreboard teams join Pyromaniac @r[team=]
scoreboard teams join Necromancer @r[team=]
scoreboard teams join Sniper @r[team=]
scoreboard teams join HappySlappy @r[team=]

scoreboard teams join WileyCyote @r[team=]
scoreboard teams join Bomberman @r[team=]
scoreboard teams join Pyromaniac @r[team=]
scoreboard teams join Necromancer @r[team=]
scoreboard teams join Sniper @r[team=]
scoreboard teams join HappySlappy @r[team=]

scoreboard teams join WileyCyote @r[team=]
scoreboard teams join Bomberman @r[team=]
scoreboard teams join Pyromaniac @r[team=]
scoreboard teams join Necromancer @r[team=]
scoreboard teams join Sniper @r[team=]
scoreboard teams join HappySlappy @r[team=]

scoreboard teams join WileyCyote @r[team=]
scoreboard teams join Bomberman @r[team=]
scoreboard teams join Pyromaniac @r[team=]
scoreboard teams join Necromancer @r[team=]
scoreboard teams join Sniper @r[team=]
scoreboard teams join HappySlappy @r[team=]

scoreboard teams join WileyCyote @r[team=]
scoreboard teams join Bomberman @r[team=]
scoreboard teams join Pyromaniac @r[team=]
scoreboard teams join Necromancer @r[team=]
scoreboard teams join Sniper @r[team=]
scoreboard teams join HappySlappy @r[team=]

scoreboard teams join WileyCyote @r[team=]
scoreboard teams join Bomberman @r[team=]
scoreboard teams join Pyromaniac @r[team=]
scoreboard teams join Necromancer @r[team=]
scoreboard teams join Sniper @r[team=]
scoreboard teams join HappySlappy @r[team=]

scoreboard teams join WileyCyote @r[team=]
scoreboard teams join Bomberman @r[team=]
scoreboard teams join Pyromaniac @r[team=]
scoreboard teams join Necromancer @r[team=]
scoreboard teams join Sniper @r[team=]
scoreboard teams join HappySlappy @r[team=]

scoreboard teams join WileyCyote @r[team=]
scoreboard teams join Bomberman @r[team=]
scoreboard teams join Pyromaniac @r[team=]
scoreboard teams join Necromancer @r[team=]
scoreboard teams join Sniper @r[team=]
scoreboard teams join HappySlappy @r[team=]

scoreboard teams join WileyCyote @r[team=]
scoreboard teams join Bomberman @r[team=]
scoreboard teams join Pyromaniac @r[team=]
scoreboard teams join Necromancer @r[team=]
scoreboard teams join Sniper @r[team=]
scoreboard teams join HappySlappy @r[team=]